module PS2_receiver( // PS2 keybord RECEIVER

    input clk,
    input reset,
    input PS2_CLK, // this clk is generated by keybord 
    // we cannot use this clk with FPGA because it is not synchronized with FPGA
    input PS2_DATA,
    //input in,

    output reg error,
    output reg [7:0]scan_code,
    output reg key_valid


);

reg [7:0]shift_reg;
reg [3:0]bit_counter;
reg [2:0]state, next_state;

// so to synchronize ps2-keybord CLK and FPGA clk WE need synchronizer
reg [1:0]clk_sync , data_sync;
reg clk_prev;

parameter IDLE   = 3'b000,       
          DATA   = 3'b001,
          PARITY = 3'b010,
          ERROR  = 3'b011,
          STOP   = 3'b100;

//assign data = shift_reg;

          
always @(posedge clk or negedge reset)begin

    if(!reset)begin
        clk_sync <= 2'b11;
        data_sync <= 2'b11;
        clk_prev <= 1'b1;
    end

    else begin

    clk_sync <= {clk_sync[0], PS2_CLK}; // 2 clk synchronizer
    data_sync <= {data_sync[0], PS2_DATA};
    clk_prev <= clk_sync[1];  // stores previous clk value

    end
end

wire falling_edge = clk_prev & ~(clk_sync[1]);
wire ps2_bit = data_sync[1];

// this will chek parity of the data with input parity if correct in parity state
wire parity = (~^shift_reg) == PS2_DATA;   // odd parity
// CHAT GPT 
//During DATA, shift_reg is only partly filled and PS2_DATA is a data bit, so parity_ok
//flips around meaninglessly. That's harmless because the FSM isn't looking.

always @(posedge clk or negedge reset)begin

    if(!reset) state <= IDLE;
    else if(falling_edge) state <= next_state; // only change ps2 fsm when we detect faliing edge of sync ps2 clk 

end

always @(posedge clk or negedge reset)begin

    if(!reset)
        bit_counter <= 0;
    
    else if(falling_edge)begin

        if(state == DATA)
            bit_counter <= bit_counter +1;
    
        else if(state != DATA)
            bit_counter <= 0;
    end
end

always @(posedge clk or negedge reset)begin

    if(!reset)begin
        error     <= 0;
        //parity    <= 0;
        scan_code <= 0;
        shift_reg <= 0;
        key_valid <= 0;
    end

    // if(state == DATA )
    //     shift_reg <= {PS2_DATA , shift_reg[7:1]};

    // if(state == PARITY)
    //     parity <= ~(^data);    

    // if(state == ERROR )
    //     error <= 1;

    // if(state == STOP )begin
    //     scan_code <= shift_reg;
    //     key_valid <= 1;
    // end

    else begin
        key_valid <= 0;
        error <= 0;
        
        if(falling_edge)begin
            case(state)

                DATA :  shift_reg <= {ps2_bit , shift_reg[7:1]};

                ERROR : error <= 1;

                STOP : if(ps2_bit)begin
                           scan_code <= shift_reg;
                           key_valid <= 1;
                       end
                       else error <= 1;
        endcase
        end
    end
     
end

always @(*)begin
    next_state = state;

    case(state)
    
    //In PS/2, the data line sits high when idle, and every frame begins with a start bit that is 0.
    //The FSM should leave IDLE when it sees that 0.
    IDLE : next_state = (!ps2_bit) ? DATA : IDLE;

    DATA : next_state = (bit_counter == 3'd7) ? PARITY : DATA;

    PARITY : next_state = (parity) ? STOP : ERROR;

    ERROR : next_state = IDLE;

    STOP : next_state = IDLE;

    default : next_state = IDLE;

    endcase
end
endmodule